import type { Metadata } from 'next'
import { Manrope } from "next/font/google";
import './globals.css'

import 'animate.css'
import Menu from '@/components/Menu'

const font = Manrope({
  weight: ["300", "400", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
});





export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body   className={`bg-[#000814] text-white ${font.className}`}>
          <Menu/>
          {children}
        </body>
    </html>
  )
}
